### PR TITLE
Fix several bugs.

### PR DESCRIPTION
**Pull request by bluefeet**

### CODE REVIEW

**Comment by bluefeet** [comment]
Hey @robn any chance you could get a release out this weekend?

**Comment by robn** [comment]
Sorry, just got back from vacation and just getting on top of everything. I'll try to look at this in the next day or two.

**Comment by bluefeet** [comment]
No worries.  I'll package it up for now in our Pinto.

**Comment by robn** [comment]
0.023 pushed to CPAN. Thanks!

**Comment by bluefeet** [comment]
Thank you sir!

**Pull request merged**
