### PR TITLE
Update Tests to use my changes to Test::Consul

### PR DESCRIPTION
**Pull request by bluefeet**
Assuming my changes in robn/Test-Consul#2 are accepted and released as version `0.005` then these changes should be released as well.

### CODE REVIEW

**Comment by bluefeet** [comment]
Note, the Travis CI checks will fail since robn/Test-Consul#2 has not been released yet.

**Comment by robn** [comment]
Waiting for Test-Consul 0.005 to hit the mirrors to make sure CI is happy. A read through looks good though.

**Comment by robn** [comment]
Consul 0.017 now on CPAN :+1:

**Comment by bluefeet** [comment]
Hmm, seems these changes did not actually make it into 0.017.  Did git bite you?  :)

**Comment by bluefeet** [comment]
If you end up releasing a `0.018` to resolve this might as well include #6.

**Comment by robn** [comment]
Aww, stupid me. I was concentrating on Travis and forgot to actually merge it. I was watching the Stranger Things finale at the same time so I'll blame that.

**Comment by robn** [comment]
0.018 for reals this time :blush:

**Comment by bluefeet** [comment]
Sounds like a perfectly reasonable excuse!  Ha.

**Pull request closed without merging**
