### PR TITLE
Add a token argument.

### PR DESCRIPTION
**Pull request by bluefeet**
Tested on a Consul cluster with ACLs and it works.  :)

### CODE REVIEW

**Comment by bluefeet** [comment]
Totally unrelated, but thought you'd like this:
https://github.com/hashicorp/consul/pull/2381

**Comment by bluefeet** [comment]
Hey man!  I'd really love to see this on CPAN.  Any chance?

**Comment by robn** [comment]
Sorry, got busy and lost track of this. I'll try to get a release done over the weekend.

(if you want co-maint, let me know :wink:)

**Comment by bluefeet** [comment]
Oh FINE, give me co-maint.  :)

**Comment by bluefeet** [comment]
Oh, you know what, I need the ACL API implemented as well.  Let me get that implemented and this and that can be released together.

**Comment by robn** [comment]
Gonna hit "merge" on this PR right now, but I'll hold off on release until you drop the ACL API or say otherwise.

(or you can use your new co-maint bit and ignore me entirely :+1:)

**Pull request merged**
